### ISSUE TITLE
Quick start, complete sample code which can generate the results in the picture.

### ISSUE THREAD

**Issue by 943fansi** [georgian-io/pyoats#23]
I am interested in anomaly detection. Your work is great, but there is a lack of detailed examples. I have installed `pyoats`, but I don't know what to do next.

**Comment by benjaminye** [comment]
Hi @943fansi! Thanks for checking out this project.

You can learn more about time series anomaly detection through our blog posts.
[Blog #1](https://medium.com/georgian-impact-blog/time-series-anomaly-detection-uncovering-clues-to-mysterious-cyber-activities-e216b4f6ac5) deals with use cases.
[Blog #2](https://medium.com/georgian-impact-blog/time-series-anomaly-detection-the-detectives-toolbox-9ef131dddaf9) outlines different techniques.

And most importantly:
[Blog #3](https://georgian-io.medium.com/time-series-anomaly-detection-a-field-study-d13b35ee4344) gives you concrete example on how to use the package. The notebook is included in the blog post.

I will close this issue once I incorporate the contents into the documentation.
Sorry for the inconvenience.


Thanks again!
Ben

**Comment by 943fansi** [comment]
Hi, @benjaminye. Thank you very much for your reply. The article is very good. I have some questions about anomaly detection that I would like to ask you. "In general, predictive methods work well for point similarities while reconstruction and distance-based methods work well for pattern similarities." Where does this conclusion come from? I am studying anomaly detection based on prediction and reconstruction methods. I am confused about the training set. Should I only use normal data or include abnormal data?
Look forward to your favorable reply!

**Comment by angeliney** [comment]
Hi @943fansi, thank you for your interest and sorry for the wait! We concluded that from our experience playing with toy data and open source datasets. But, I would suggest to definitely verify that information yourself, since it maybe different for different datasets. For training set, we suggest to just use normal data in the case of prediction and reconstruction method, especially because the models are first trying to learn what normal looks like and we're using the predictive or reconstruction error as a gauge of abnormality.

**Comment by 943fansi** [comment]
@angeliney Thanks.
