### ISSUE TITLE
[Question] Is this package no longer maintained?

### ISSUE THREAD

**Issue by thuyng-ing** [georgian-io/pyoats#38]
Thanks for creating this awesome library. I want to ask if this package is still maintained? Thanks

**Comment by angeliney** [comment]
Thank you for your kind words! Yes, we're still maintaining the library, but it might take some time to address all issues because we're not actively working on maintaining this library anymore. Your feedback is important, so please don't hesitate to report any specific problems or suggestions you have. We appreciate your support!

**Comment by thuyng-ing** [comment]
Could you update the darts version to 0.26.0 (this lib's darts is 0.23.0)? Thank you very much!
